### ISSUE TITLE
Client never initializes on .NET Framework 4.8 MVC Application

### ISSUE THREAD

**Issue by rkajbaf-experientgroup** [launchdarkly/dotnet-core#31]
**Is this a support request?**
No,

**Describe the bug**
Fails to ever initialize in a .NET Framework 4.8 Web Application on the latest version (8.0).  **Downgrading to 7.1 resolves the problem.**

**To reproduce**
Try on a .NET Framework MVC Application.  Client will never initialize.

**Expected behavior**
Should initialize.

**Logs**
If applicable, add any log output related to your problem.

**SDK version**
8.0

**Language version, developer tools**
.NET Framework v4.8

**OS/platform**
Windows

**Additional context**
**Downgrading to 7.1 resolves the problem.**

**Comment by tanderson-ld** [comment]
Tried to reproduce this issue by creating a .NET Framework 4.8 class library and then using that in a console application.  It appears to have worked fine, so at the moment we cannot reproduce this.

**Comment by jsonbailey** [comment]
@JoshuaMS7 I can recreate the error you are experiencing and am looking at it today.

**Comment by JoshuaMS7** [comment]
Another error found is that couldn't load launchdarkly.commonsdk v7.0.0 when initializing connection after upgraded the launchdarkly serversdk to v8.92 to fix my performance issue but actually it's implicit reference to launchdarkly.commonsdk v7.0.1 and no way to be downgraded. Think this is an error from launchdarkly for serversdk v8.92?

**Comment by jsonbailey** [comment]
Yes, there is currently a mismatch in the common.sdk package version numbers. I have an update in review and I'll let you know when a new version is released with the fix. Long term we plan to make some changes to help prevent the need for binding redirects but there are a few other items ahead of that work.

**Comment by JoshuaMS7** [comment]
After upgraded serversdk to v8.10.0 and it caused error for "System.IO.FileLoadException: Could not load file or assembly 'LaunchDarkly.CommonSdk, Version=7.1.0.0, Culture=neutral, ..." instead of Version=7.0.0 in this time. I'm trying to apply transition reference to LaunchDarkly.CommonSdk v7.1.0.0 and it caused "System.IO.FileLoadException: Could not load file or assembly 'LaunchDarkly.ServerSdk, Version=8.10.0.0" error. Can help to check?

**Comment by JoshuaMS7** [comment]
Yeah being solved the load assembly issue but it seems caused the error below. 

LaunchDarkly: 2025-07-14 12:20:31.812 +10:00 [LaunchDarkly.Sdk.DataSource] DEBUG: Making GET request to EventSource URI https://stream.launchdarkly.com/all
2025-07-14 12:20:31.8449|INFO | 129|-LaunchDarkly: 2025-07-14 12:20:31.844 +10:00 [LaunchDarkly.Sdk.DataSource] DEBUG: Response status: 200
2025-07-14 12:20:31.8449|INFO | 129|-LaunchDarkly: 2025-07-14 12:20:31.844 +10:00 [LaunchDarkly.Sdk.DataSource] DEBUG: EventSource Opened
2025-07-14 12:20:31.8449|INFO | 129|-LaunchDarkly: 2025-07-14 12:20:31.844 +10:00 [LaunchDarkly.Sdk.DataSource] DEBUG: Reading UTF-8 stream without string conversion
2025-07-14 12:20:31.8449|INFO | 129|-LaunchDarkly: 2025-07-14 12:20:31.853 +10:00 [LaunchDarkly.Sdk.DataSource] DEBUG: Received event "put"
2025-07-14 12:20:31.8449|INFO | 129|-LaunchDarkly: 2025-07-14 12:20:31.853 +10:00 [LaunchDarkly.Sdk.DataSource] ERROR: Unexpected error in stream processing: System.IO.FileLoadException: Could not load file or assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
2025-07-14 12:20:31.8449|INFO | 129|-LaunchDarkly: 2025-07-14 12:20:31.853 +10:00 [LaunchDarkly.Sdk.DataSource] DEBUG:    at LaunchDarkly.Sdk.Server.Internal.DataSources.StreamProcessorEvents.ParsePutData(Byte[] json)
   at LaunchDarkly.Sdk.Server.Internal.DataSources.StreamingDataSource.HandleMessage(String messageType, Byte[] messageData)
   at LaunchDarkly.Sdk.Server.Internal.DataSources.StreamingDataSource.OnMessage(Object sender, MessageReceivedEventArgs e)

Finally getting the error below. 
2025-07-14 12:21:53.7767|INFO | 129|-LaunchDarkly: 2025-07-14 12:21:53.776 +10:00 [LaunchDarkly.Sdk.DataSource] INFO: Waiting 28001 milliseconds before reconnecting...

May i know is any idea since it was only happen in website app (IIS based) instead of window app?

**Comment by JoshuaMS7** [comment]
Just wondering why System.Memory load too low version to v4.0.1.1 which dot net is using v4.6.3 and causing incompatible issue in my website? Actually serversdk v8.5.1 is working fine in my window app and only caused system.memory issue when applying in IIS based app. Thanks your concern.

**Comment by jsonbailey** [comment]
I have tested 8.10.0 using the `ASP.NET Web Application (.NET Framework)` template in Visual Studio 2022 and targeted `.Net Framework 4.8`. After adding the latest (8.10.0) LaunchDarkly Server SDK I verified that it was working in IIS. You might need to look at your installed packages and setup a binding redirect if needed so that it can source the proper packages.

**Comment by JoshuaMS7** [comment]
Mine .Net framework 4.7.2 and it references to System.Memory v4.0.1.2. But it's still caused incompatible issue for System.Memory with binding redirect below in webconfig.

<dependentAssembly>
   <assemblyIdentity name="System.Memory" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
   <bindingRedirect oldVersion="0.0.0.0-4.0.1.2" newVersion="4.0.1.2" />
</dependentAssembly>

**Comment by jsonbailey** [comment]
I have created a new net framework 4.7.2 project and installed the LaunchDarkly.ServerSdk (8.10.0) and the client was able to initialize successfully so I cannot reproduce your error. You will need to share the Nuget packages and their versions so I can help. It is possible another package is causing a conflict or a version was not properly updated.

When tracing through the dependencies on Nuget for [LaunchDarkly.ServerSdk (8.10.0)](https://www.nuget.org/packages/LaunchDarkly.ServerSdk#dependencies-body-tab) I see they eventually lead to System.Memory (4.5.5) through the `System.Collections.Immutable`, `System.Text.Json`, and `LaunchDarkly.Logging -> Microsoft.Extensions.Logging.Abstractions` packages dependencies. 

If you don't want to share this information here, you can open a support ticket when logged into your LaunchDarkly account and provide the details there along with a link to this issue so it can get escalated the SDK team.
