### ISSUE TITLE
.NET client fails to load on Windows WPF apps, assumes it is on MAUI

### ISSUE THREAD

**Issue by rbakhshi** [launchdarkly/dotnet-core#60]
**Describe the bug**
Client sdk 5.0.0 fails to load in a WPF app in .NET8 `net8.0-windows`.

**To reproduce**
- Create a simple WPF all using .NET8 (TargetFramework `net8.0-windows`).
- Add launchdarkly client sdk 5.0.0
- Init the sdk: `LdClient.Init(context)`

**Expected behavior**
It should not fail

**Logs**
```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Maui.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Maui.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Microsoft.Maui.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at LaunchDarkly.Sdk.Client.PlatformSpecific.PlatformConnectivity.get_LdNetworkAccess()
   at LaunchDarkly.Sdk.Client.Internal.DataSources.DefaultConnectivityStateManager.UpdateConnectedStatus()
   at LaunchDarkly.Sdk.Client.Internal.DataSources.DefaultConnectivityStateManager..ctor()
   at LaunchDarkly.Sdk.Client.Internal.Factory.CreateConnectivityStateManager(Configuration configuration)
   at LaunchDarkly.Sdk.Client.LdClient..ctor(Configuration configuration, Context initialContext, TimeSpan startWaitTime)
   at LaunchDarkly.Sdk.Client.LdClient.CreateInstance(Configuration configuration, Context initialContext, TimeSpan maxWaitTime)
   at LaunchDarkly.Sdk.Client.LdClient.Init(Configuration config, Context initialContext, TimeSpan maxWaitTime)
```

**SDK version**
LD 5.0.0

**Language version, developer tools**
```
> dotnet --version
8.0.401

```

**OS/platform**
Windows 10

**Additional context**

**Comment by megamechanic** [comment]
The same exception for Windows App SDK

**Comment by tanderson-ld** [comment]
We have a possible workaround for you while we refactor some of our packaging logic.  Could you try the following in your csproj file?  This adds `HintPath`s to resolve the dependencies to the netstandard2.0 dlls in the distribution.

```
<ItemGroup>
    <PackageReference Include="LaunchDarkly.ClientSdk" Version="5.3.0" GeneratePathProperty="true" ExcludeAssets="Compile;Runtime;Build"/>
    <PackageReference Include="LaunchDarkly.CommonSdk" Version="7.0.0" GeneratePathProperty="true" ExcludeAssets="Compile;Runtime;Build"/>
    <PackageReference Include="LaunchDarkly.InternalSdk" Version="3.4.0" GeneratePathProperty="true" ExcludeAssets="Compile;Runtime;Build"/>
    <PackageReference Include="LaunchDarkly.Logging" Version="2.0.0" GeneratePathProperty="true" ExcludeAssets="Compile;Runtime;Build"/>
    <PackageReference Include="LaunchDarkly.EventSource" Version="5.0.1" GeneratePathProperty="true" ExcludeAssets="Compile;Runtime;Build"/>
    <Reference Include ="LaunchDarkly.ClientSdk">
          <HintPath>$(PkgLaunchDarkly_ClientSdk)\lib\netstandard2.0\LaunchDarkly.ClientSdk.dll</HintPath>
      </Reference>
      <Reference Include ="LaunchDarkly.CommonSdk">
        <HintPath>$(PkgLaunchDarkly_CommonSdk)\lib\netstandard2.0\LaunchDarkly.CommonSdk.dll</HintPath>
      </Reference>
      <Reference Include ="LaunchDarkly.InternalSdk">
          <HintPath>$(PkgLaunchDarkly_InternalSdk)\lib\netstandard2.0\LaunchDarkly.InternalSdk.dll</HintPath>
      </Reference>
      <Reference Include ="LaunchDarkly.Logging">
          <HintPath>$(PkgLaunchDarkly_Logging)\lib\netstandard2.0\LaunchDarkly.Logging.dll</HintPath>
      </Reference>
      <Reference Include ="LaunchDarkly.EventSource">
          <HintPath>$(PkgLaunchDarkly_EventSource)\lib\netstandard2.0\LaunchDarkly.EventSource.dll</HintPath>
      </Reference>
  </ItemGroup>
```
